angular.module("templateMaker").config(["$routeProvider", function ($routeProvider) {
        $routeProvider.when('/main', {
            template: "<h1>{{templateList.length==0 ? \"Drag in your templates\" : \"Templates\"}}</h1>\n    <div>\n    <div ng-show=\"templateList.length>0\">\n    <div class=\"ui relaxed divided list\">\n      <div class=\"item\" ng-repeat=\"(key, item) in templateList track by $index\">\n        <i class=\"large file outline middle aligned icon\"></i>\n        <div class=\"content\">\n          <div class=\"header\">{{item.name}}</div>\n          <div class=\"description\">{{item.size}}</div>\n        </div>\n      </div>\n    </div>\n    </div>\n\n\n    <file-dropper ng-show=\"templateList.length==0\" ondrop=\"dropTemplateFiles()\" label=\"Drop files here\"></file-dropper>\n<br>\n<button class=\"ui button\" ng-if=\"templateList.length>0\" ng-click=\"blankSlate()\">Change templates</button>\n    <button class=\"ui button\" ng-click=\"templateLoaded()&&navigateTo('#/fields')\" ng-class=\"{disabled: templateList.length==0, primary: templateList.length>0}\">Continue</button>\n    </div>"
        })
            .when('/fields', {
            template: "\n    <h1>Fields</h1>\n    <div class=\"ui form\">\n      <div class=\"ui field\" ng-repeat=\"field in fields track by $index\">\n        <label>{{field.clean}}</label>\n        <tpl-textarea ng-model=\"field.model\" field=\"field\" ng-change=\"updateFieldValue(field, field.model)\" ng-if=\"field.type=='textarea'\"></tpl-textarea>\n        <tpl-textbox ng-model=\"field.model\" ng-change=\"updateFieldValue(field, field.model)\" ng-if=\"field.type=='text'\"></tpl-textbox>\n        <tpl-date ng-model=\"field.model\" ng-change=\"updateFieldValue(field, field.model)\" ng-if=\"field.type=='date'\"/></tpl-date>\n        </div>\n      </div><br>\n      <button ng-click=\"areAllFieldsCompleted()&&navigateTo('#/export')\" class=\"ui\" ng-class=\"{'disabled button': !areAllFieldsCompleted(), 'primary button':areAllFieldsCompleted()}\">Review and export</button>\n    "
        })
            .when('/export', {
            template: "\n    <div ng-show=\"templateList.length==0\">\n      There are no templates to export.\n      </div>\n    <div ng-show=\"templateList.length>0\">\n    <div class=\"ui relaxed divided list\">\n      <div class=\"item\" ng-repeat=\"(key, item) in templateList track by $index\">\n      <div class=\"right floated content\">\n\n        <div class=\"ui buttons\">\n          <div class=\"ui button\" ng-click=\"exportDownloadSingleFile(item)\">Download</div>\n          <div class=\"ui simple dropdown icon button\">\n            <i class=\"dropdown icon\"></i>\n            <div class=\"menu\">\n              <div class=\"item\" ng-click=\"previewHTML(item)\">Open in browser</div>\n              </div>\n            </div>\n          </div>\n      </div>\n\n        <i class=\"large file outline middle aligned icon\"></i>\n        <div class=\"content\">\n          <div class=\"header\">{{item.name}}</div>\n          <div class=\"description\">{{item.size}}</div>\n        </div>\n      </div>\n    </div>\n<br>\n<button class=\"ui button\" ng-click=\"exportAllTemplates()\">Download All</button>\n<button class=\"ui button\" ng-click=\"blankSlate()\">Start over</button>\n\n    </div>\n\n    "
        })
            .otherwise({ redirectTo: "/main" });
    }]);
